---
- hosts: localhost
  become: yes
  tasks:
  - name: update and install apache
    apt:
      name: apache2
      state: present
      update_cache: yes
  notify:
  - start apache
  - name: installing php packages
    apt:
      name: "{{ item }}"
      state: present
    loop:
     - php
     - libapache2-mod-php
     - php-mcrypt
     - php-mysql
     - php-cli
  notify:
  - restart apache
  - name: copy php
    copy:
      src: info.php
      dest: /var/www/html/info.php
  handlers:
  - name: restart apache 
    service:
      name: apache2
      state: restarted
  - name: start apache
    service:
      name: apache2
      enabled: yes
      state: started 
